### ISSUE TITLE
HTTP Tunnels

### ISSUE THREAD

**Issue by ghost** [bbc/draft-ohanlon-transport-info-header#1]
The document should have some text to describe how to deal with HTTP CONNECT, or not deal and list it as a consideration.

**Comment by piersoh** [comment]
The HTTP CONNECT case needs to be added to section 4, but basically there’s not many options as it "restrict its behavior to blind forwarding of packets, in both directions, until the tunnel is closed”[rfc7231#section-4.3.6]. For unencrypted exchanges a proxy could filter traffic according to local policy as mentioned in Section 4.
