### ISSUE TITLE
Is sub-second resolution appropriate?

### ISSUE THREAD

**Issue by ghost** [bbc/draft-ohanlon-transport-info-header#3]
Implementations may find that acquiring sub-second accuracy expensive and/or difficult to achieve. Allowing for a variety of resolutions may remove the requirement, for example using [RFC3339](https://tools.ietf.org/html/rfc3339) might be a better option.

**Comment by piersoh** [comment]
I think that sub-second time is appropriate, but choice of the actual time representation format is a good question - RFC 3339 looks promising. I think most web servers proxies don’t have an issue with providing sub second clocks - though how accurate they are varies - E.g. Nginx’s $msec variable is based on a stored copy of the clock which is updated at arbitrary intervals so doesn’t result in system call for gettimeofday() and slowing everything down, but it is less accurate though it’s probably good enough for most purposes.

**Comment by ghost** [comment]
I think with #6 merged, we can close this.
