### ISSUE TITLE
Could this be used for both request and response?

### ISSUE THREAD

**Issue by ghost** [bbc/draft-ohanlon-transport-info-header#4]
At Thursday's httpbis meeting, @ianswett suggested this as a plausible use cases being serving different responses based on client properties.

My initial thoughts is that there's no reason not to do this.

**Comment by piersoh** [comment]
Agreed - though for most browser clients this information is not available to them. However for other types clients this should be possible.

**Comment by piersoh** [comment]
We need to add additional explanation as to the implications of utilising the header in Request or Responses, and how behaviour and privacy aspects differ.
